#-------------------------------
# General Site Settings
title: Maryum Mateen
logo: logo1.png # You can add own logo.
description: Maryum's Personal Blog


#-------------------------------
# Author Settings
author:
  name: Maryum Mateen
  image: 01.jpg
  say-hello: Hello, Iâ€™m <strong>Maryum Mateen</strong>
  bio: I'm a student at the <strong>University of Houston</strong>. I'm currently pursuing a degree in <strong>Computer Science</strong> with a minor in <strong>Data Science</strong> and <strong>Math</strong>. <a href="#">Resume</a>


#-------------------------------
# Contact links
twitter: https://twitter.com/MateenMaryum # Add your Twitter handle
facebook: https://www.facebook.com/people/Maryum-Mateen/100006609678816 # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/maryummateen_/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: maryummateen_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
